### ISSUE TITLE
Feature request - be able to see raw images in the viewer even after correcting for uneven illumination

### ISSUE THREAD

**Issue by aschoenauer-sebag** [TissueMAPS/TmUI#1]
Hi,

Once images have been metaextracted and uneven illumination has been corrected, it would be great to still be able to visualize raw images in the web browser viewer, ie to have the possibility to choose between displaying corrected images and raw images.

Thanks!
Alice

**Comment by riccardomurri** [comment]
This issue was moved to TissueMAPS/TissueMAPS#125
